# Generated by Django 5.2.4 on 2025-07-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_id_alter_country_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=128, null=True, verbose_name='Capital'),
        ),
        migrations.AddField(
            model_name='country',
            name='topLevelDomain',
            field=models.CharField(max_length=3, null=True, verbose_name='Top Level Domain'),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='countries.region'),
        ),
    ]
